language: node_js
node_js:
  - 12
  - 14
jobs:
  os: linux
  services: postgresql
  # - osx
  # - windows
# addons:
#   homebrew:
#     packages:
#       - postgresql
#   apt:
#     packages:
#       - postgresql
# services:
#   - postgresql
script:
  - yarn lint
  - yarn test
  - yarn e2e